services:
  docs:
    image: edu_ecosystem_local_docs
    container_name: edu_ecosystem_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./edu_ecosystem:/app/edu_ecosystem:z
    ports:
      - '9000:9000'
    command: /start-docs
