# Generated by Django 6.0.3 on 2026-07-20 03:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('nodes', models.JSONField(blank=True, default=dict, verbose_name='nodes')),
                ('edges', models.JSONField(blank=True, default=list, verbose_name='edges')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('pending_approval', 'Pending Approval')], default='pending', max_length=20, verbose_name='status')),
                ('state_data', models.JSONField(blank=True, default=dict, verbose_name='state data')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'db_table': 'workflow_runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=100, verbose_name='node id')),
                ('node_type', models.CharField(max_length=100, verbose_name='node type')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='status')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='input data')),
                ('output_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='output data')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_logs', to='workflows.workflowrun', verbose_name='workflow run')),
            ],
            options={
                'verbose_name': 'Node Run Log',
                'verbose_name_plural': 'Node Run Logs',
                'db_table': 'node_run_logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
