# Generated by Django 6.0.3 on 2026-07-20 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_noderunlog_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=255, verbose_name='document name')),
                ('text_content', models.TextField(verbose_name='text content')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='embedding')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'document_chunks',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
