# Generated by Django 6.0.3 on 2026-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='project_name',
            field=models.CharField(blank=True, default='Default Project', max_length=100, null=True, verbose_name='project name'),
        ),
    ]
